---
- name: rename AD01
  hosts: 10.0.0.111
  tasks:
    - name: Rename AD01
      ansible.windows.win_powershell:
        script: |
          Rename-Computer -NewName "AD01" -Force
      register: rename_result
      async: 60
      poll: 0
      
- name: rename AD02
  hosts: 10.0.0.112
  tasks:
    - name: Rename AD02
      ansible.windows.win_powershell:
        script: |
          Rename-Computer -NewName "AD02" -Force
      register: rename_result
      async: 60
      poll: 0
- name: rename DHCP01
  hosts: 10.0.0.113
  tasks:
    - name: Rename DHCP01
      ansible.windows.win_powershell:
        script: |
          Rename-Computer -NewName "DHCP01" -Force
      register: rename_result
      async: 60
      poll: 0
- name: rename FILE01
  hosts: 10.0.0.114
  tasks:
    - name: Rename FILE01
      ansible.windows.win_powershell:
        script: |
          Rename-Computer -NewName "FILE01" -Force
      register: rename_result
      async: 60
      poll: 0
- name: rename CA01
  hosts: 10.0.0.115
  tasks:
    - name: Rename FILE01
      ansible.windows.win_powershell:
        script: |
          Rename-Computer -NewName "CA01" -Force
      register: rename_result
      async: 60
      poll: 0

- name: Proxmox host
  hosts: proxmox03   
  tasks:
    - name: Reboot VM
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: yhp82bws
        api_host: 10.0.0.13
        name: "{{ item }}"
        node: proxmox03
        state: restarted
      loop:
        - CA01
        - FILE01
        - DHCP01
        - AD01
        - AD02




