---
- name: rename AD
  hosts: 10.0.0.111
  tasks:
    - name: Rename vms
      ansible.windows.win_powershell:
        script: |
          Rename-Computer -NewName "AD01" -Force
      register: rename_result
      async: 60
      poll: 0
    - name: reboot vm
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: yhp82bws
        api_host: 10.0.0.13
        name: "{{ host_to_name[ansible_host] }}"
        node: proxmox03
        state: rebooted
