---
- name: Rename and reboot servers
  hosts: windows
  serial: 1
  order: inventory
  vars:
    host_to_name:
      "10.0.0.111": "AD01"
      "10.0.0.112": "AD02"
      "10.0.0.113": "DHCP01"
      "10.0.0.114": "FILE01"
      "10.0.0.115": "CA01"
  tasks:
    - name: Rename VM
      ansible.windows.win_powershell:
        script: |
          Rename-Computer -NewName "{{ host_to_name[ansible_host] }}" -Force
      async: 60
      poll: 0

- name: Proxmox host
  hosts: proxmox03   
  tasks:
    - name: Reboot VM
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: yhp82bws
        api_host: 10.0.0.13
        name: "{{ item }}"
        timeout: 300
        node: proxmox03
        state: restarted
      loop:
        - CA01
        - FILE01
        - DHCP01
        - AD01
        - AD02




