---
- name: rename servers
  hosts: windows
  serial: 1
  order: inventory
  vars:
      host_to_name:
        "10.0.0.111": "AD01"
        "10.0.0.112": "AD02"
        "10.0.0.113": "DHCP01"
        "10.0.0.114": "FILE01"
        "10.0.0.115": "CA01"
  tasks:
    - name: Rename vms
      ansible.builtin.command: powershell.exe -Command "Rename-Computer -NewName '{{ host_to_name[ansible_host] }}' -Force"
      register: rename_result
      async: 60
      poll: 0
    - name: reboot vm
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: yhp82bws
        api_host: 10.0.0.13
        name: "{{ host_to_name[ansible_host] }}"
        node: proxmox03
        state: rebooted
