---      
- name: AD01 SERVER
  hosts: 10.0.0.111 
  tasks:
    - name: Create new Windows domain in a new forest with specific parameters and reboot in post task
      microsoft.ad.domain:
        create_dns_delegation: false
        database_path:  F:\Database
        dns_domain_name: KMC.local
        domain_mode: Win2012R2
        domain_netbios_name: KMC
        forest_mode: Win2012R2
        safe_mode_password: P@ssw0rd!
        sysvol_path:  G:\Sysvol
        domain_log_path: H:\Logs
        reboot: true
      register: domain_install
    
- name: Add DNS forwarder
  hosts: 10.0.0.111
  collections:
    - community.windows
  tasks:
    - name: Set conditional forwarder to 1.1.1.1
      ansible.windows.win_powershell:
        script: |
          Add-DnsServerConditionalForwarderZone -Name "Forwarder" -MasterServers "1.1.1.1"

- name: AD02 SERVER
  hosts: 10.0.0.112
  tasks:
    - name: Install AD Domain Services and RSAT-AD-PowerShell
      ansible.windows.win_feature:
        name:
          - AD-Domain-Services
          - RSAT-AD-PowerShell
        state: present
        include_management_tools: yes
        include_sub_features: yes
   
- name: AD02 SERVER
  hosts: 10.0.0.112 
  tasks:
    - name: Add ad02 to the existing domain
      microsoft.ad.membership:
        dns_domain_name: KMC.local
        hostname: AD02
        domain_admin_user: administrator@KMC.local
        domain_admin_password: P@ssw0rd!
        state: domain
        reboot: true
- name: Promote AD02 to domain controller
  hosts: 10.0.0.112 
  tasks:
    - name: Promote AD02 to a domain controller
      microsoft.ad.domain_controller:
        dns_domain_name: KMC.local
        domain_admin_user: administrator@KMC.local
        domain_admin_password: P@ssw0rd!
        safe_mode_password: P@ssw0rd!
        state: domain_controller
        sysvol_path:  G:\Sysvol
        domain_log_path: H:\Logs
        database_path: F:\Database
        reboot: true
        
- name: DHCP server install dhcp feature
  hosts: 10.0.0.113
  tasks:
    - name: Install DHCP Server role
      ansible.windows.win_feature:
        name: DHCP
        state: present
        include_management_tools: yes
        include_sub_features: yes
      register: dhcp_install
      
- name: Install Certificate authority
  hosts: 10.0.0.115
  tasks:
    - name: Install Certificate Authority role
      ansible.windows.win_feature:
        name: ADCS-Cert-Authority
        state: present
