---
- name: rename servers
  hosts: windows
  serial: 1
  order: inventory
  vars:
      host_to_name:
        "10.0.0.111": "AD01"
        "10.0.0.112": "AD02"
        "10.0.0.113": "DHCP01"
        "10.0.0.114": "FILE01"
        "10.0.0.115": "CA01"
  tasks:
    - name: Rename vms
      ansible.windows.win_powershell:
        script: |
          Rename-Computer -NewName "{{ host_to_name[ansible_host] }}" -Force
      register: rename_result
      async: 60
      poll: 0
    - name: Start VM
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: yhp82bws
        api_host: 10.0.0.13
        name: "{{ item }}"
        node: proxmox03
        state: rebooted
      loop:
        - CA01
        - FILE01
        - DHCP01
        - AD01
        - AD02
      
- name: AD SERVER
  hosts: 10.0.0.111
  become: no  
  tasks:
    - name: Create new Windows domain in a new forest with specific parameters and reboot in post task
      microsoft.ad.domain:
        create_dns_delegation: false
        database_path:  F:\Database
        dns_domain_name: KMC.local
        domain_mode: Win2012R2
        domain_netbios_name: KMC
        forest_mode: Win2012R2
        safe_mode_password: P@ssw0rd!
        sysvol_path:  G:\Sysvol
      register: domain_install
    
    - name: Reboot host if install requires it
      ansible.windows.win_reboot:
      when: domain_install.reboot_required
