---      
- name: AD01 SERVER
  hosts: 10.0.0.111 
  tasks:
    - name: Create new Windows domain in a new forest with specific parameters and reboot in post task
      microsoft.ad.domain:
        create_dns_delegation: false
        database_path:  F:\Database
        dns_domain_name: KMC.local
        domain_mode: Win2012R2
        domain_netbios_name: KMC
        forest_mode: Win2012R2
        safe_mode_password: P@ssw0rd!
        sysvol_path:  G:\Sysvol
        reboot: true
      register: domain_install
      
 - name: ADD DNS forwarder
  hosts: 10.0.0.111
  tasks:   
    - name: Ensure forwarder has specific DNS servers
  community.windows.win_dns_zone:
    name: KMC.local
    type: forwarder
    dns_servers:
      - 1.1.1.1
      - 8.8.8.8
