---      
- name: AD01 SERVER
  hosts: 10.0.0.111 
  tasks:
    - name: Create new Windows domain in a new forest with specific parameters and reboot in post task
      microsoft.ad.domain:
        create_dns_delegation: false
        database_path:  F:\Database
        dns_domain_name: KMC.local
        domain_mode: Win2012R2
        domain_netbios_name: KMC
        forest_mode: Win2012R2
        safe_mode_password: P@ssw0rd!
        sysvol_path:  G:\Sysvol
        reboot: true
      register: domain_install
    
- name: Add DNS forwarder
  hosts: 10.0.0.111
  collections:
    - community.windows
  tasks:
    - name: Set conditional forwarder to 1.1.1.1
      ansible.windows.win_powershell:
        script: |
          Add-DnsServerConditionalForwarderZone -Name "Forwarder" -MasterServers "1.1.1.1"

- name: AD02 SERVER
  hosts: 10.0.0.112 
  tasks:
    - name: Add ad02 to the existing domain
      microsoft.ad.membership:
        dns_domain_name: KMC.local
        hostname: AD02
        domain_admin_user: administrator@KMC.local
        domain_admin_password: P@ssw0rd!
        state: domain
        reboot: true
