---
- name: Proxmox host
  hosts: proxmox03  # Runs on the control node, using the Proxmox API
  become: no  # No sudo needed for API calls
  tasks:
    - name: Create VM 
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: yhp82bws
        api_host: 10.0.0.13
        name: batman
        node: proxmox03
        sata:
          sata0: 'local-lvm:10,format=raw'
        bios: seabios
        ide:
          ide0: "local:iso/Win2022auto.iso,media=cdrom"
          ide1: "local:iso/virtio-win-0.1.266.iso,media=cdrom"
        cores: 2
        memory: 4096
        net:
          net0: 'virtio,bridge=vmbr0,rate=200'
        ostype: win11
