---
- name: Proxmox host
  hosts: proxmox03  # Runs on the control node, using the Proxmox API
  become: no  # No sudo needed for API calls
  tasks:
    - name: Create VM with 1 10GB SATA disk and an EFI disk, with Secure Boot disabled by default
      community.general.proxmox_kvm:
      api_user: root@pam
      api_password: yhp82bws
      api_host: 10.0.0.13
      name: batman
      node: proxmox03
      sata:
        sata0: 'VMs_LVM:10,format=raw'
      bios: Seabios
      efidisk0:
      storage: 'local-lvm'
      format: raw
      efitype: 4m
      pre_enrolled_keys: false
