---
- name: Proxmox host
  hosts: proxmox03  # Runs on the control node, using the Proxmox API
  become: no  # No sudo needed for API calls
  tasks:
    - name: Create VM
      community.general.proxmox:
        node: proxmox03
        api_user: root@pam
        api_password: yhp82bws
        api_host: proxmox03
        password: yhp82bws
        hostname: AD
        disk: 'local-lvm:20'
        memory: 2048  # Recommended
        cores: 2      # Recommended
        state: present
