---
- name: Proxmox host
  hosts: proxmox03  
  become: no  
  tasks:
    - name: Create VM 
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: yhp82bws
        api_host: 10.0.0.13
        name: "{{ item }}"
        node: proxmox03
        sata:
          sata0: 'local-lvm:70,format=raw'
        bios: seabios
        ide:
          ide0: "local:iso/Win2022DatacenterDesktopExperienceAuto.iso,media=cdrom"
          ide1: "local:iso/virtio-win-0.1.266.iso,media=cdrom"
        cores: 2
        memory: 4096
        net:
          net0: 'virtio,bridge=vmbr0,rate=200'
        ostype: win11
        state: present
      loop:
        - AD
        - DHCP
        - FILE
        - AD2
    - name: Start VM
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: yhp82bws
        api_host: 10.0.0.13
        name: "{{ item }}"
        node: proxmox03
        state: started
      loop:
        - AD
        - DHCP
        - FILE
        - AD2
    - name: Wait for Windows installation to complete
      ansible.builtin.pause:
        minutes: 15
