---
- name: Proxmox host
  hosts: proxmox03  # Runs on the control node, using the Proxmox API
  become: no  # No sudo needed for API calls
  tasks:
    - name: Create VM
      community.general.proxmox_kvm:
        api_host: 10.0.0.13
	      api_port: 8006
        api_password: yhp82bws
        api_user: root@pam
        name: TEST
	      node: proxmo03
	    net:
	      net0: 'virtio,bridge=vmbr1,rate=200'
	    sata:
	      sata0: 'local:10,format=raw'
	      bios: Seabios
        efidisk0:
	      storage: "local-lvm"
	      format: raw
	      efitype: 4m
	      pre_enrolled_keys: false
